version: "3.9"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
